### ISSUE TITLE
Photos are no longer being pulled from Facebook

### ISSUE THREAD

**Issue by stephenmcghee** [carlsverre/jquery-facebook-page-photos#1]
This must have happened recently. Facebook may have changed the way their photo gallery functions?
I'm getting a couple errors in the console, and I'm assuming somethings wrong on their side:

![fbphotos](https://cloud.githubusercontent.com/assets/4974044/8681920/4a1b7ee6-2a38-11e5-98cb-984c9bee7b92.jpg)

Any ideas?
Thanks!

**Comment by carlsverre** [comment]
Hm, I think this might be a permissions issue.  I am using the code successfully on one of my client sites and have not updated it recently.  It looks like your album is not public which is required for FBPagePhotos to work

**Comment by stephenmcghee** [comment]
Hi,
I just took a look at the album and it appears to be public?
https://www.facebook.com/media/set/?set=a.553364944720040

And here is the site in question:
http://www.wcmarketplace.ca/photos

Thanks again for your help.

**Comment by carlsverre** [comment]
Ah I see the issue - if its a private photo album you probably need to allocate a basic access token for the Facebook graph.  More info here:

https://developers.facebook.com/docs/facebook-login/access-tokens

You can see the relevant issue by trying to access your album via the graph:

http://graph.facebook.com/553364944720040

You can use the token like so:

```
$(".selector").FBPagePhotos({
    access_token: "YOUR ACCESS TOKEN",
    album_id: ALBUM_ID
})
```

**Comment by carlsverre** [comment]
Whoops - just realized that this code doesn't have the access_token thing.  Ill add it real quick

**Comment by carlsverre** [comment]
fixed in latest release

**Comment by stephenmcghee** [comment]
We will try it out.
Thanks for your help.
